package com.campussphere.entity.registration;

public enum NotificationType {
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    REGISTRATION_CANCELLED,
    WAITLISTED,
    WAITLIST_PROMOTED,
    INVITATION_RECEIVED,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,
    INVITATION_CANCELLED,
    ATTENDANCE_SESSION_OPENED,
    ATTENDANCE_SESSION_CLOSED,
    ATTENDANCE_RECORDED,
    ATTENDANCE_UPDATED,
    ATTENDANCE_UNDONE,
    QR_TOKEN_GENERATED,
    QR_TOKEN_INVALIDATED,
    CERTIFICATE_ISSUED,
    CERTIFICATE_REVOKED,
    CERTIFICATE_READY
}
