package com.campussphere.entity.registration;

public enum NotificationType {
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    REGISTRATION_CANCELLED,
    WAITLISTED,
    WAITLIST_PROMOTED,
    INVITATION_RECEIVED,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,
    INVITATION_CANCELLED
}
