export const APP_ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  unauthorized: '/unauthorized',
  accessDenied: '/access-denied',
  auth: '/auth',
  dashboard: '/dashboard',
  analytics: '/dashboard/analytics',
  reports: '/dashboard/reports',
  profileSetup: '/profile/setup',
  events: '/dashboard/events',
  registrations: '/dashboard/registrations',
  attendance: '/dashboard/attendance',
  attendanceScanner: '/dashboard/attendance/scanner',
  attendanceHistory: '/dashboard/attendance/history',
  attendanceReports: '/dashboard/attendance/reports',
  certificates: '/dashboard/certificates',
  certificateTemplates: '/dashboard/certificates/templates',
  certificateGenerated: '/dashboard/certificates/generated',
  certificateSettings: '/dashboard/certificates/settings',
  certificateVerification: '/dashboard/certificates/verify',
  certificatePublicVerify: '/verify/:token'
};
